apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: sahelim04/simple-api:latest
          ports:
            - containerPort: 3000
          resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: POSTGRES_HOST
            value: postgres
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USERNAME
            value: postgres
          - name: POSTGRES_DB
            value: simple-blog-api
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD