# Specify Base Image
FROM docker.io/node:18-alpine

# Work Directory
WORKDIR /user/app

# Copy everything in my current folder and paste inside work directory
COPY . .

# Install Dependencies
RUN npm install
 
# Startup Command
CMD ["npm", "start"]